title: Computing Summer Camp
description: Prep material for the Data Science MSc. at Barcelona Graduate School of Economics. All source files, included slides, are available in the Github repository.
show_downloads: false
theme: jekyll-theme-cayman
